/*
----------------------------JAVA----------------------------

Code made by: Angel Manuel Miranda Asturias
Done on: 2020

This program is free software: you can redistribute it or modify

Use it as you like and have fun reading it ^^

------------------------------------------------------------
 */
package Interface;

import java.awt.FlowLayout;
import project2.Project2;

/**
 *
 * @author manuel
 */
public class Principal extends javax.swing.JFrame {
    
    /*
        activePanel = 0 -> None
        activePanel = 1 -> User menu
        activePanel = 2 -> Books menu
        activePanel = 3 -> Category menu
        activePanel = 4 -> Reports menu
    */
    private int activePanel = 0;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        pnlContent.setLayout(new FlowLayout());
        
        this.setContentPane(this.jPanel1);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        btnClose1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        btnReports = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlUser = new javax.swing.JPanel();
        btnUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlBooks = new javax.swing.JPanel();
        btnBooks = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pnlCategory = new javax.swing.JPanel();
        btnCategory = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1135, 646));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContent.setOpaque(false);
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 820, 590));

        btnClose1.setFont(new java.awt.Font("Laksaman", 1, 48)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 0, 0));
        btnClose1.setText("X");
        btnClose1.setBorder(null);
        btnClose1.setBorderPainted(false);
        btnClose1.setContentAreaFilled(false);
        btnClose1.setFocusPainted(false);
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 80, 60));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back (1).png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setFocusable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlReports.setBackground(new java.awt.Color(255, 255, 255));
        pnlReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReportsMouseClicked(evt);
            }
        });
        pnlReports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/repo.png"))); // NOI18N
        btnReports.setBorderPainted(false);
        btnReports.setContentAreaFilled(false);
        btnReports.setFocusPainted(false);
        pnlReports.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REPORTES");
        pnlReports.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, 40));

        jPanel2.add(pnlReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 280, 80));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUserMouseClicked(evt);
            }
        });
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user (2).png"))); // NOI18N
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.setFocusPainted(false);
        pnlUser.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("USUARIO");
        pnlUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, 40));

        jPanel2.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 80));

        pnlBooks.setBackground(new java.awt.Color(255, 255, 255));
        pnlBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBooksMouseClicked(evt);
            }
        });
        pnlBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/book (1).png"))); // NOI18N
        btnBooks.setBorderPainted(false);
        btnBooks.setContentAreaFilled(false);
        btnBooks.setFocusPainted(false);
        pnlBooks.add(btnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 60));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LIBROS");
        pnlBooks.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, 40));

        jPanel2.add(pnlBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 80));

        pnlCategory.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCategoryMouseClicked(evt);
            }
        });
        pnlCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arch.png"))); // NOI18N
        btnCategory.setBorderPainted(false);
        btnCategory.setContentAreaFilled(false);
        btnCategory.setFocusPainted(false);
        pnlCategory.add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 80, 60));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CATEGORIAS");
        pnlCategory.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, 40));

        jPanel2.add(pnlCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBooksMouseClicked
        if(activePanel != 2){
            activePanel = 2;

            System.out.println("Books");

            // Change panel
            pnlContent.removeAll();
            pnlBooksP booksPanel = new pnlBooksP(this);
            pnlContent.add(booksPanel);
            pnlContent.revalidate();
            pnlContent.repaint();
        }
    }//GEN-LAST:event_pnlBooksMouseClicked

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void pnlUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserMouseClicked
        if(activePanel != 1){
            activePanel = 1;
            
            System.out.println("User");
            
            // Change Panel
            pnlContent.removeAll();
            pnlUserP userPanel = new pnlUserP(this);
            pnlContent.add(userPanel);
            pnlContent.revalidate();
            pnlContent.repaint();
        }        
    }//GEN-LAST:event_pnlUserMouseClicked

    private void pnlCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCategoryMouseClicked
        if(activePanel != 3){
            activePanel = 3;
            
            System.out.println("Category");
            
            // Change Panel
            pnlContent.removeAll();
            pnlCategoryP categoryPanel = new pnlCategoryP(this);
            pnlContent.add(categoryPanel);
            pnlContent.revalidate();
            pnlContent.repaint();
        }        
    }//GEN-LAST:event_pnlCategoryMouseClicked

    private void pnlReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportsMouseClicked
        if(activePanel != 4){
            activePanel = 4;
            
            System.out.println("Reports");
            
            Project2.avl.GenerateTree();
            
            // Change Panel
            pnlContent.removeAll();
            pnlReportsP reportsPanel = new pnlReportsP(this);
            pnlContent.add(reportsPanel);
            pnlContent.revalidate();
            pnlContent.repaint();
        }
    }//GEN-LAST:event_pnlReportsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Login l = new Login();
        this.dispose();

        l.show();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBooks;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JPanel pnlCategory;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlUser;
    // End of variables declaration//GEN-END:variables
}
