/*
----------------------------JAVA----------------------------

Code made by: Angel Manuel Miranda Asturias
Done on: 2020

This program is free software: you can redistribute it or modify

Use it as you like and have fun reading it ^^

------------------------------------------------------------
 */
package Interface;

import project2.Project2;
import static project2.Project2.auxiliarBlock;

/**
 *
 * @author manuel
 */
public class SocketsFrame extends javax.swing.JFrame {

    /**
     * Creates new form SocketsFrame
     */
    public SocketsFrame() {
        initComponents();
        this.setContentPane(this.jPanel1);
        setLocationRelativeTo(null);
        
        txtIPFriend.setText(Project2.IP);
        
        if(Project2.state){
            btnSendBlock.setEnabled(true);
            lblActive.setText("ACTIVO");
            btnConnect.setEnabled(false);
            txtIPFriend.enable(false);
        }else{
            btnSendBlock.setEnabled(false);
            lblActive.setText("NO ACTIVO");
            btnConnect.setEnabled(true);
            txtIPFriend.enable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose1 = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblActive = new javax.swing.JLabel();
        btnSendBlock = new javax.swing.JButton();
        txtIPFriend = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        txtIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose1.setFont(new java.awt.Font("Laksaman", 1, 48)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 0, 0));
        btnClose1.setText("X");
        btnClose1.setBorder(null);
        btnClose1.setBorderPainted(false);
        btnClose1.setContentAreaFilled(false);
        btnClose1.setFocusPainted(false);
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, 60));

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CONEXIÓN");
        pnlLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("IP AMIGA:");
        pnlLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 140, 20));

        lblActive.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblActive.setForeground(new java.awt.Color(0, 0, 0));
        lblActive.setText("NO ACTIVO");
        pnlLogin.add(lblActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 360, 70));

        btnSendBlock.setBackground(new java.awt.Color(102, 102, 255));
        btnSendBlock.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSendBlock.setForeground(new java.awt.Color(255, 255, 255));
        btnSendBlock.setText("ENVIAR BLOQUE");
        btnSendBlock.setBorderPainted(false);
        btnSendBlock.setFocusPainted(false);
        btnSendBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBlockActionPerformed(evt);
            }
        });
        pnlLogin.add(btnSendBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 460, 50));

        txtIPFriend.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pnlLogin.add(txtIPFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado:");
        pnlLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 140, 20));

        btnConnect.setBackground(new java.awt.Color(55, 224, 76));
        btnConnect.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnConnect.setForeground(new java.awt.Color(255, 255, 255));
        btnConnect.setText("CONECTAR");
        btnConnect.setBorderPainted(false);
        btnConnect.setFocusPainted(false);
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        pnlLogin.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 530, 50));

        txtIP.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pnlLogin.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 260, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TU IP:");
        pnlLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 140, 20));

        jPanel1.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnClose1ActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        
        Project2.state = true;
        
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnSendBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBlockActionPerformed

        auxiliarBlock.GenerateBlock();
        
    }//GEN-LAST:event_btnSendBlockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocketsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocketsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocketsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocketsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocketsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSendBlock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActive;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtIPFriend;
    // End of variables declaration//GEN-END:variables
}
